services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kv_store_service
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local